package com.example.shoptify.common

val PRODUCT_RESPONSE: String = "PRODUCT_RESPONSE"
val CATEGORY_RESPONSE: String = "CATEGORY_RESPONSE"
val PRODUCT_STATUS_RESPONSE: String = "PRODUCT_STATUS_RESPONSE"
val VENDOR_RESPONSE: String = "VENDOR_RESPONSE"

val DISPLAY_LIST = 1
val DISPLAY_GRID = 2

